# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish as NPM Package

on:
  push:
    branches:
      - master
#   release:
#     types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn build
      #       - run: yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
## The following action does not work because project is not scoped like "@rafibarash/simple-physics-engine"
## https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages

# publish-gpr:
#   needs: build
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 12
#         registry-url: https://npm.pkg.github.com/
#     - run: yarn install --frozen-lockfile
#     - run: yarn build
#     - run: yarn publish
#       env:
#         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
